---

- name: Install buildbot
  apt:
    name: "{{ buildbot_package }}"
    state: present

- name: Install extra packages for buildbot
  apt:
    name: "{{ buildbot_extra_packages }}"
    state: present

- name: Install buildbot_extra_pip_packages
  pip:
    name: "{{ buildbot_extra_pip_packages }}"
    executable: pip3
    state: present

- name: Create /etc/default/buildbot
  template:
    src: Ubuntu.default.j2
    dest: /etc/default/buildbot
    validate: sh -n %s
  notify: Restart buildbot
