---

- name: Install buildbot
  pkgng:
    name: "{{ buildbot_package }}"
    state: present

- name: Install extra packages for buildbot
  pkgng:
    name: "{{ buildbot_extra_packages }}"
    state: present

- name: Create /etc/rc.conf.d/buildbot
  template:
    src: FreeBSD.rcd.j2
    dest: /etc/rc.conf.d/buildbot
    validate: sh -n %s
  notify: Restart buildbot
