---
- name: Converge
  hosts: all
  tasks:
    - name: "Include molecule"
      include_role:
        name: "molecule"

- name: Import playbook buildbot
  import_playbook: playbooks/buildbot.yml

- name: Import playbook worker
  import_playbook: playbooks/worker.yml
